### PR TITLE
Music Album Class

### LINKED ISSUE #6: [1pt] TM#2 Create MusicAlbum class
- Create the class in a separate .rb file
- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.

### PR DESCRIPTION
**Pull request by kwesiObuobi**
## Hi team
In this PR, I did the following:
- Created the `MusicAlbum` class in a separate .rb file
- In its constructor method, I added all the class properties visible in the diagram,

### CODE REVIEW

**Comment by skabeo** [comment]
Hi @kwesiObuobi 

Kindly add this pull request to it's respective issue

**Review by skabeo — APPROVED** [review]
Hi @kwesiObuobi 
 
Your project is complete     There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 




## Highlights 

 No linter errors. ✔️ 
 You used correct Git-Flow. ✔️ 
 Good Commit Messages ✔️ 
 MusicAlbum class implemented according to the requirement ✔️

**Comment by kwesiObuobi** [comment]
I'm gonna hit you up for that...

**Review by Yacoubou-seidou — APPROVED** [review]
Hi @kwesiObuobi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
image

## Highlights 
:+1: adding music-album-class

Cheers and Happy coding!👏👏👏_

**Pull request merged**
